# kubectl apply -f ./chapter_10/kubia-service-headless.yaml

apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  # The service is headless.
  clusterIP: None
  selector:
    matchLabels:
      app: kubia
  ports:
    - name: http
      port: 80
