# kubectl create serviceaccount foo
# kubectl apply -f ./chapter_12/curl-custom-serviceaccount.yaml

apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-serviceaccount
spec:
  serviceAccountName: foo
  containers:
    - name: main
      image: tutum/curl
      command: ["sleep", "9999999"]
    - name: ambassador
      image: luksa/kubectl-proxy:1.6.2
