# kubectl create ns foo
# kubectl apply -f ./chapter_12/role-service-reader.yaml -n foo

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: foo
  name: service-reader
rules:
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources: ["services"]