# kubectl create -f ./chapter_04/kubia-multi-port-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  # Always redirect client to the same pod based on the client ip
  sessionAffinity: ClientIP
  ports:
    # Port name is required when multiple ports are specified
    - name: http
      # The port this service will be available on
      port: 80
      # The container port the service will forward to
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    # All pods with the app=kubia label will be part of this service
    app: kubia
