# kubectl create -f chapter_04/kubia-liveness-probe.yaml

apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
    - image: luksa/kubia-unhealthy
      name: kubia
      # liveness probe restarts the container if it returns an error
      livenessProbe:
        httpGet:
          path: /
          port: 8080
